WiseTechGlobal/WTG.Analyzers

build/Global.props

Update copyright years.

---

WTG.Analyzers.sln

Mostly just intended to remove the reference to ReleaseInfo.xml, but seems the solution file hasn't had a good dusting in a while.

Remove reference to ReleaseInfo.xml from the solution file.

---

CommonAssemblyInfo.cs
WTG.Analyzers.Test/RuleSetTest.cs

Added test as mentioned in https://github.com/WiseTechGlobal/WTG.Analyzers/pull/19

Added test to ensure that WarnAll.ruleset is up-to-date.

---

WTG.Analyzers.Test/TestData/LinqAnalyzer/Any/Diagnostics.xml
WTG.Analyzers.Test/TestData/LinqAnalyzer/Any/Result.cs
WTG.Analyzers.Test/TestData/LinqAnalyzer/Any/Source.cs
WTG.Analyzers/Analyzers/Linq/LinqMethod.cs
WTG.Analyzers/Analyzers/Linq/Method/AnyLinqMethod.cs

#17
As discussed, I left out the exception for `ConcurrentDictionary<,>`.

WTG3002 should suggest IsEmpty rather than Count > 0 when available.

---

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/BlockBody/Diagnostics.xml
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/BlockBody/Result.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/BlockBody/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/DifferentOverload/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/ExpressionBody/Diagnostics.xml
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/ExpressionBody/Result.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/ExpressionBody/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/ModifyingArguments/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/ModifyingResult/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/OnlyOneAccessorNeedsToBeMeaningful/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/Prefixed/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/Suffixed/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/Wrapped/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/WrongName/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/WrongTarget/Source.cs
WTG.Analyzers.Test/WTG.Analyzers.Test.csproj
WTG.Analyzers/Analyzers/PointlessOverride/PointlessOverrideAnalyzer.cs
WTG.Analyzers/Analyzers/PointlessOverride/PointlessOverrideCodeFixProvider.cs
WTG.Analyzers/Analyzers/PointlessOverride/PointlessOverrideFixAllProvider.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml
WTG.Analyzers/build/WarnAll.ruleset

An implementation of the rule requested in #24.
It covers all the auto-generated cases and several trivial variations, but there are still a lot of simple variations that it doesn't detect. I figure we can leave them out until we find real world situations where they happen.

Pointless override

---

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Equality/Diagnostics.xml
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Equality/Result.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Equality/Source.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Expression/Diagnostics.xml
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Expression/Result.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Expression/Source.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/FindNodeTie/Diagnostics.xml
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/FindNodeTie/Result.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/FindNodeTie/Source.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/IgnoreNullable/Source.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/IgnoresImplicitConversions/Source.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/IgnoresInclusiveOperators/Source.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Inequality/Diagnostics.xml
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Inequality/Result.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Inequality/Source.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/LinqExpression/Diagnostics.xml
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/LinqExpression/Result.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/LinqExpression/Source.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Trivia/Diagnostics.xml
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Trivia/Result.cs
WTG.Analyzers.Test/TestData/NullComparisonAnalyzer/Trivia/Source.cs
WTG.Analyzers.Test/WTG.Analyzers.Test.csproj
WTG.Analyzers/Analyzers/BooleanComparison/BooleanComparisonCodeFixProvider.cs
WTG.Analyzers/Analyzers/NullComparison/NullComparisonAnalyzer.cs
WTG.Analyzers/Analyzers/NullComparison/NullComparisonCodeFixProvider.cs
WTG.Analyzers/Analyzers/NullComparison/NullLiteralVisitor.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml
WTG.Analyzers/build/WarnAll.ruleset

Add analyzer to detect comparing value types against null literal

---

WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/AsyncBlockBody/Diagnostics.xml
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/AsyncBlockBody/Result.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/AsyncBlockBody/Source.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/AsyncExpressionBody/Diagnostics.xml
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/AsyncExpressionBody/Result.cs
WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/AsyncExpressionBody/Source.cs
WTG.Analyzers/Analyzers/PointlessOverride/PointlessOverrideAnalyzer.cs

Extend WTG3007 to include async methods.

---

WTG.Analyzers.TestFramework.nuspec

Fix TestFramework target path in NuGet package

---

WTG.Analyzers.Test/VersioningTest.cs
WTG.Analyzers.Utils.nuspec
build-packages.cmd

Add NuGet package for Utils

---

WTG.Analyzers.Test/TestData/ArrayAnalyzer/NoArrayEmpty/Source.cs
WTG.Analyzers/Analyzers/Array/ArrayAnalyzer.cs

WTG3004: Cancel analysis if Array.Empty is unavailable.

---

WTG.Analyzers.TestFramework.nuspec
WTG.Analyzers.Utils.nuspec
WTG.Analyzers.nuspec
appveyor.yml
build-packages.cmd

Record the exact commit used in the nuget package metadata.
```xml
<package>
<metadata>
...
<repository type="git" url="https://github.com/WiseTechGlobal/WTG.Analyzers" commit="ecf91ea665a36e0ffb1215606f15ece67ff9243a" />
```

Track commit id in nuget packages.

---

WTG.Analyzers.Test/AnalyzerOnlyTest.cs
WTG.Analyzers.Test/TestData/ConditionalOperandAnalyzer/IncorrectLine/Diagnostics.xml
WTG.Analyzers.Test/TestData/ConditionalOperandAnalyzer/IncorrectLine/Source.cs
WTG.Analyzers.Test/TestData/ConditionalOperandAnalyzer/MultilineOperands/Diagnostics.xml
WTG.Analyzers.Test/TestData/ConditionalOperandAnalyzer/MultilineOperands/Source.cs
WTG.Analyzers.Test/TestData/ConditionalOperandAnalyzer/SingleLine.Source.cs
WTG.Analyzers.Test/WTG.Analyzers.Test.csproj
WTG.Analyzers/Analyzers/ConditionalOperand/ConditionalOperandAnalyzer.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml
WTG.Analyzers/build/WarnAll.ruleset

Conditional expression operands should occupy a single line.

---

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers.Test/TestData/DiscardThrowAnalyzer/DiscardThrow/Diagnostics.xml
WTG.Analyzers.Test/TestData/DiscardThrowAnalyzer/DiscardThrow/Result.cs
WTG.Analyzers.Test/TestData/DiscardThrowAnalyzer/DiscardThrow/Source.cs
WTG.Analyzers.Test/TestData/DiscardThrowAnalyzer/NotDiscard.Source.cs
WTG.Analyzers.Test/TestData/DiscardThrowAnalyzer/Trivia/Diagnostics.xml
WTG.Analyzers.Test/TestData/DiscardThrowAnalyzer/Trivia/Result.cs
WTG.Analyzers.Test/TestData/DiscardThrowAnalyzer/Trivia/Source.cs
WTG.Analyzers/Analyzers/DiscardThrow/DiscardThrowAnalyzer.cs
WTG.Analyzers/Analyzers/DiscardThrow/DiscardThrowCodeFixProvider.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml
WTG.Analyzers/build/WarnAll.ruleset

Avoid discard-coalesce-throw.

---

WTG.Analyzers.Test/TestData/CompletedTaskAnalyzer/NoCompletedTask.Source.cs
WTG.Analyzers/Analyzers/CompletedTask/CompletedTaskAnalyzer.cs

Don't report WTG3009 if Task.Completed is not defined.

---

WTG.Analyzers.TestFramework.nuspec
WTG.Analyzers.Utils.nuspec
WTG.Analyzers.nuspec

Update nuspec to follow new standard

---

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/CompletedTask/Diagnostics.xml
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/CompletedTask/Result.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/CompletedTask/Source.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/ConfigureAwait/Diagnostics.xml
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/ConfigureAwait/Result.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/ConfigureAwait/Source.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/FromCanceled/Diagnostics.xml
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/FromCanceled/Source.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/FromException/Diagnostics.xml
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/FromException/Result.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/FromException/Source.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/FromResult/Diagnostics.xml
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/FromResult/Result.cs
WTG.Analyzers.Test/TestData/AwaitCompletedAnalyzer/FromResult/Source.cs
WTG.Analyzers.Utils.Test/SymbolExtensionsTest.cs
WTG.Analyzers.Utils/SymbolExtensions.cs
WTG.Analyzers.Utils/WellKnownTypeNames.cs
WTG.Analyzers/Analyzers/Async/AsyncAnalyzer.cs
WTG.Analyzers/Analyzers/AwaitCompleted/AwaitCompletedAnalyzer.cs
WTG.Analyzers/Analyzers/AwaitCompleted/AwaitCompletedCodeFixProvider.cs
WTG.Analyzers/Analyzers/CompletedTask/CompletedTaskAnalyzer.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml
WTG.Analyzers/build/WarnAll.ruleset

Trivially completed tasks

---

WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/Generic/Result.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsCodeFixProvider.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsFixAllProvider.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsHelper.cs

Improved exception message for generic requires called without an explicit message.

---

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Instance.Source.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/IsMatch/Diagnostics.xml
WTG.Analyzers.Test/TestData/RegexAnalyzer/IsMatch/Result.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/IsMatch/Source.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Mask/Diagnostics.xml
WTG.Analyzers.Test/TestData/RegexAnalyzer/Mask/Result.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Mask/Source.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Match/Diagnostics.xml
WTG.Analyzers.Test/TestData/RegexAnalyzer/Match/Result.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Match/Source.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Matches/Diagnostics.xml
WTG.Analyzers.Test/TestData/RegexAnalyzer/Matches/Result.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Matches/Source.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Replace/Diagnostics.xml
WTG.Analyzers.Test/TestData/RegexAnalyzer/Replace/Result.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Replace/Source.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Split/Diagnostics.xml
WTG.Analyzers.Test/TestData/RegexAnalyzer/Split/Result.cs
WTG.Analyzers.Test/TestData/RegexAnalyzer/Split/Source.cs
WTG.Analyzers.TestFramework/Helpers/ModelUtils.cs
WTG.Analyzers/Analyzers/Regex/RegexAnalyzer.cs
WTG.Analyzers/Analyzers/Regex/RegexCodeFixProvider.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml

Detect RegexOptions.Compiled in static Regex methods.

---

WTG.Analyzers/Analyzers/CodeContracts/CodeContractsHelper.cs

Avoid Workspace assembly during analysis.

---

WTG.Analyzers.Test/TestData/EmitAnalyzer/Overflow/Diagnostics.xml
WTG.Analyzers.Test/TestData/EmitAnalyzer/Overflow/Result.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/Overflow/Source.cs
WTG.Analyzers/Analyzers/Emit/EmitConversionVisitor.cs

Fallback to generating a cast operation.

---

Directory.Build.props
WTG.Analyzers.TestFramework.Test/WTG.Analyzers.TestFramework.Test.csproj
WTG.Analyzers.TestFramework/WTG.Analyzers.TestFramework.csproj
WTG.Analyzers.Utils/WTG.Analyzers.Utils.csproj
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsAnalyzer.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsHelper.cs
WTG.Analyzers/Analyzers/Var/VarAnalyzer.cs
WTG.Analyzers/FutureSyntaxKinds.cs
appveyor.yml

Update Roslyn to 2.10.

---

WTG.Analyzers.Test/TestData/BooleanLiteralAnalyzer/BoxedMethodArgument/Source.cs
WTG.Analyzers.Test/TestData/BooleanLiteralAnalyzer/IndexArgument/Source.cs
WTG.Analyzers.Test/TestData/BooleanLiteralAnalyzer/ParamsMethodArgument/Source.cs
WTG.Analyzers.Test/TestData/BooleanLiteralAnalyzer/SingleMethodArgument/Source.cs
WTG.Analyzers.Test/TestData/BooleanLiteralAnalyzer/TupleArgument/Source.cs
WTG.Analyzers/Analyzers/BooleanLiteral/ArgumentListExtensions.cs
WTG.Analyzers/Analyzers/BooleanLiteral/BooleanLiteralAnalyzer.cs

Fix crashes in WTG1018

---

.github/workflows/build.yaml
.github/workflows/release.yaml
WTG.Analyzers.Test/WTG.Analyzers.Test.csproj
WTG.Analyzers.TestFramework.Test/WTG.Analyzers.TestFramework.Test.csproj
WTG.Analyzers.Utils.Test/WTG.Analyzers.Utils.Test.csproj

Includes cf5c8df which I accidentally pushed to master :(

Update to .NET 5 SDK

---

.github/workflows/build.yaml
.github/workflows/release.yaml

Replace GITHUB_SHA env var with github.sha Actions expression

---

WTG.Analyzers.Test/TestData/WhitespaceAnalyzer/LineEndingsNewLine/Diagnostics.xml
WTG.Analyzers.Test/TestData/WhitespaceAnalyzer/LineEndingsNewLineCarriageReturn/Diagnostics.xml
WTG.Analyzers/Analyzers/Whitespace/WhitespaceAnalyzer.cs
WTG.Analyzers/Analyzers/Whitespace/WhitespaceCodeFixProvider.cs

Combine all EOL issues for the same file into a single diagnostic.

---

.github/workflows/build.yaml
.github/workflows/release.yaml

Update .NET SDK from 5.0.103 to 5.0.301 (latest stable).

Update .NET SDK

---

.editorconfig
src/WTG.Analyzers.Test/TestData/EmitAnalyzer/ComplexOpCode/Source.cs
src/WTG.Analyzers.sln
src/WTG.Analyzers/Analyzers/Emit/EmitAnalyzer.cs

Fix NRE for complex OpCodes.

---

src/WTG.Analyzers.Test/TestData/CompletedTaskAnalyzer/TaskTypeNotDefined/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/CompletedTaskAnalyzer/TaskTypeNotDefined/Source.cs
src/WTG.Analyzers.TestFramework/Helpers/ModelUtils.cs
src/WTG.Analyzers.TestFramework/TestData/SampleDataSet.cs
src/WTG.Analyzers/Analyzers/CompletedTask/CompletedTaskAnalyzer.cs

Fixes #172.
Tracked by WI00461839.

Fix AD0001 crash in CompletedTaskAnalyzer when System.Threading.Tasks.Task does not exist.

---

src/WTG.Analyzers.Test/AnalyzerOnlyTest.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/AsEnumerable/Item.Source.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/AsEnumerable/Set.Source.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/AsEnumerable/Value.Source.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Enumerable/Item/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Enumerable/Item/Source.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Enumerable/Set/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Enumerable/Set/Source.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Enumerable/Value/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Enumerable/Value/Source.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Queryable/Item.Source.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Queryable/Set.Source.cs
src/WTG.Analyzers.Test/TestData/QueryLinqAnalyzer/Queryable/Value.Source.cs
src/WTG.Analyzers.Utils/WellKnownTypeNames.cs
src/WTG.Analyzers/Analyzers/Linq/LinqMethod.cs
src/WTG.Analyzers/Analyzers/QueryLinq/QueryLinqAnalyzer.cs
src/WTG.Analyzers/Rules/Rules.g.cs
src/WTG.Analyzers/Rules/Rules.xml

Closes #160 .
<sub>WI00444563</sub>

Warn against patterns that cause unexpected conversion from `IQueryable<>` to `IEnumerable<>`.

---

src/WTG.Analyzers.Test/TestData/PublicTupleTypeAnalyzer/NullableTuple/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/PublicTupleTypeAnalyzer/NullableTuple/Source.cs
src/WTG.Analyzers/Analyzers/PublicTupleType/PublicTupleTypeAnalyzer.cs

Handle nullable tuple types.

---

src/WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/NestedMethods/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/Properties/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/VarAnalyzer/Locals/Result.cs
src/WTG.Analyzers.Test/TestData/VarAnalyzer/Locals/Source.cs
src/WTG.Analyzers.Test/TestData/VarAnalyzer/Nullable.Source.cs
src/WTG.Analyzers.Test/TestData/VarAnalyzer/Out/Result.cs
src/WTG.Analyzers.Test/TestData/VarAnalyzer/Out/Source.cs
src/WTG.Analyzers.TestFramework/Helpers/ModelUtils.cs
src/WTG.Analyzers.TestFramework/TestData/SampleDataSet.cs
src/WTG.Analyzers.TestFramework/TestData/SampleDataSetOptions.cs
src/WTG.Analyzers.Utils/WellKnownTypeNames.cs
src/WTG.Analyzers/Analyzers/Var/VarAnalyzer.cs

WTG1002 false positive with NRT.

---

src/WTG.Analyzers.Test/AnalyzerOnlyTest.cs
src/WTG.Analyzers.Test/TestData/MSBuildLocatorAnalyzer/NotWellKnownClass/Source.cs
src/WTG.Analyzers.Test/TestData/MSBuildLocatorAnalyzer/RegisterDefaults/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/MSBuildLocatorAnalyzer/RegisterDefaults/Source.cs
src/WTG.Analyzers.Test/TestData/MSBuildLocatorAnalyzer/RegisterInstance/Source.cs
src/WTG.Analyzers.Test/WTG.Analyzers.Test.csproj
src/WTG.Analyzers/Analyzers/MSBuildLocatorAnalyzer/MSBuildLocatorAnalyzer.cs
src/WTG.Analyzers/Rules/Rules.g.cs
src/WTG.Analyzers/Rules/Rules.xml
src/WTG.Analyzers/WTG.Analyzers.csproj

I haven't done a code-fix here, but I don't think it's strictly necessary.
Closes #186.
Tracked by WI00546062.

Add Analyzer to forbid MSBuildLocator.RegisterDefaults()

---

.editorconfig
src/WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/Sealed/Source.cs
src/WTG.Analyzers/Analyzers/PointlessOverride/PointlessOverrideAnalyzer.cs

WI00577538: WTG3007 should allow sealed overrides

---

src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/Partial/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/Partial/Result.cs
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/Partial/Source.cs
src/WTG.Analyzers/Analyzers/Visibility/VisibilityAnalyzer.cs

Fixes #205.
Tracked by WI00600488.

Relax WTG1001 for C# 9 partial methods

---

src/WTG.Analyzers.TestFramework/Helpers/CodeFixer.cs
src/WTG.Analyzers/Analyzers/BooleanLiteralCombining/BooleanLiteralCombiningAnalyzer.cs
src/WTG.Analyzers/Analyzers/BooleanLiteralCombining/BooleanLiteralCombiningCodeFixProvider.cs
src/WTG.Analyzers/Analyzers/FileSystemPaths/FileSystemPathsAnalyzer.cs
src/WTG.Analyzers/Analyzers/FileSystemPaths/FileSystemPathsCodeFixProvider.cs
src/WTG.Analyzers/Utils/CommonDiagnosticProperties.cs

Should not register a code fix that does not make any changes.

---

src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/Compilation/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/Compilation/Result.cs
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/Compilation/Source.cs
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/FileScopedNamespace/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/FileScopedNamespace/Result.cs
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/FileScopedNamespace/Source.cs
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/Namespace/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/Namespace/Result.cs
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/TopLevelInternal/Namespace/Source.cs
src/WTG.Analyzers.Test/WTG.Analyzers.Test.csproj
src/WTG.Analyzers.TestFramework/WTG.Analyzers.TestFramework.csproj
src/WTG.Analyzers.Utils.Test/DirectiveHelperTest.cs
src/WTG.Analyzers.Utils.Test/FutureSyntaxKindsTest.cs
src/WTG.Analyzers.Utils/FutureSyntaxKinds.cs
src/WTG.Analyzers/Analyzers/Visibility/VisibilityAnalyzer.cs

Support file scoped namespaces in WTG1006.

---

.github/workflows/build.yaml
.github/workflows/release.yaml

Update action versions.
