WiseTechGlobal/WTG.Analyzers

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/ArraysOfMultiDimensionalArrayCreation/Diagnostics.xml
WTG.Analyzers.Test/TestData/ArrayAnalyzer/ArraysOfMultiDimensionalArrayCreation/Result.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/ArraysOfMultiDimensionalArrayCreation/Source.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationInAttribute/Source.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithAmbiguities/Diagnostics.xml
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithAmbiguities/Result.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithAmbiguities/Source.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithTopLevelUsing/Diagnostics.xml
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithTopLevelUsing/Result.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithTopLevelUsing/Source.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithoutUsing/Diagnostics.xml
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithoutUsing/Result.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/EmptyArrayCreationWithoutUsing/Source.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/IncompleteCode/Diagnostics.xml
WTG.Analyzers.Test/TestData/ArrayAnalyzer/IncompleteCode/Source.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/JaggedArrayCreation/Diagnostics.xml
WTG.Analyzers.Test/TestData/ArrayAnalyzer/JaggedArrayCreation/Result.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/JaggedArrayCreation/Source.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/MultiDimenstionalArrayCreation/Source.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/SizedArrayCreation/Source.cs
WTG.Analyzers.TestFramework/Helpers/CodeFixer.cs
WTG.Analyzers/Analyzers/Array/ArrayAnalyzer.cs
WTG.Analyzers/Analyzers/Array/ArrayCodeFixProvider.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml
WTG.Analyzers/build/WarnAll.ruleset

**Analyzer:**
- Generates a diagnostic on `new T[0]`.
- Ignores multi-dimensional arrays
- Ignores jagged arrays
- Ignores arrays created in attributes, where function calls are not available.
**Code Fix:**
- Where `System.Array` is in scope, replaces `new T[0]` with `Array.Empty<T>()`
- Where `System.Array` is not in scope, replaces `new T[0]` with `System.Array.Empty<T>()`.
I couldn't find a sane and simple way to insert a using for `System`, and also don't really want to have to deal with that in a source file where `Array` is ambiguous.

Create analyzer to prefer Array.Empty<T>() over new T[0].

---

WTG.Analyzers.Test/TestData/ArrayAnalyzer/ArrayAsArgument/Diagnostics.xml
WTG.Analyzers.Test/TestData/ArrayAnalyzer/ArrayAsArgument/Result.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/ArrayAsArgument/Source.cs
WTG.Analyzers/Analyzers/Array/ArrayCodeFixProvider.cs

Fix exception in ArrayCodeFixProvider when an empty array is passed as an argument.

Fix exception in ArrayCodeFixProvider

---

WTG.Analyzers.Test/TestData/VisibilityAnalyzer/DetectAndFix/Diagnostics.xml
WTG.Analyzers.Test/TestData/VisibilityAnalyzer/DetectAndFix/Result.cs
WTG.Analyzers.Test/TestData/VisibilityAnalyzer/DetectAndFix/Source.cs
WTG.Analyzers/Analyzers/Visibility/VisibilityAnalyzer.cs

Now that C# 7.2 supports `private protected` we should probably make sure `private` isn't combined with `protected` before suggesting it be removed.

Add support for private protected.

---

LICENSE.md
WTG.Analyzers.TestFramework.nuspec
WTG.Analyzers.nuspec
build/Global.props

Updated copyright year references that were missed in #12 
These files were already specifying just a single year, so left them as such. not sure if they should be changed to 2016-2018.

Copyright year

---

WTG.Analyzers.Test/TestData/WhitespaceAnalyzer/LeadingWhitespace/Diagnostics.xml
WTG.Analyzers.Test/TestData/WhitespaceAnalyzer/LeadingWhitespace/Result.cs
WTG.Analyzers.Test/TestData/WhitespaceAnalyzer/LeadingWhitespace/Source.cs
WTG.Analyzers/Analyzers/Whitespace/WhitespaceAnalyzer.cs
WTG.Analyzers/Analyzers/Whitespace/WhitespaceCodeFixProvider.cs

If a doc-comment spans more than one line, only the first line is being checked by WTG1004, this change fixes that.

Fix leading whitespace in doc-comments.

---

appveyor.yml
build/Global.props

Longer term, I need to find a way to get rid of `WTG_ANALYZERS_VERSION`.
Short term, I've just bumped it along with the rest.

Bump version to 2.0.4, add deployment to gallery when tagged

---

WTG.Analyzers/Rules/Rules.xml

The TFS references haven't been relevant since moving to GitHub.

Removed some comments referencing TFS.

---

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers/Analyzers/BooleanComparison/BooleanComparisonCodeFixProvider.cs
WTG.Analyzers/Analyzers/Linq/LinqCodeFixProvider.cs
WTG.Analyzers/Analyzers/RegionDirective/RegionDirectiveCodeFixProvider.cs

Just cleaned up a few copy-paste issues.

Normalize ExportCodeFixProviderAttribute.Name.

---

WTG.Analyzers.Test/TestData/ArrayAnalyzer/SizedArrayCreation/Source.cs
WTG.Analyzers/Analyzers/Array/ArrayAnalyzer.cs

This change addresses the false-positive in WTG3004 when the size is provided by a non-constant value that has been cast or where a +/- unary operator is applied.

Fixed false positive on non-constant size.

---

WTG.Analyzers.TestFramework.nuspec
WTG.Analyzers.nuspec
appveyor.yml
build/Global.props

Bump version number for new release.
Removed version numbers from the nuspec files, it's out of date and gets overridden anyway.

Bump version number to 2.0.5

---

WTG.Analyzers.sln

Disables building WTG.Analyzers.TestFramework.Test in release builds.

Don't build TestFramework.Test in release.

---

WTG.Analyzers.Utils.Test/ExpressionSyntaxFactoryTest.cs
WTG.Analyzers.Utils/ExpressionSyntaxFactory.cs

Well that was embarrassing.
We use `Interlocked.CompareExchange` to avoid a race condition, but then proceed to re-introduce the effect of the race. (the severity is very low though, it just means we may create more objects than we really need to.)

Fixed race in nameof cache.

---

WTG.Analyzers.Test/TestData/ArrayAnalyzer/InitializerExpression/Diagnostics.xml
WTG.Analyzers.Test/TestData/ArrayAnalyzer/InitializerExpression/Result.cs
WTG.Analyzers.Test/TestData/ArrayAnalyzer/InitializerExpression/Source.cs
WTG.Analyzers/Analyzers/Array/ArrayAnalyzer.cs
WTG.Analyzers/Analyzers/Array/ArrayCodeFixProvider.cs

Fixes #46.
There has to be a better way to do the `.Parent.Parent.Parent` bit somehow...

WTG3004: Warn on array initializers.

---

.editorconfig
WTG.Analyzers.Utils/WTG.Analyzers.Utils.csproj
WTG.Analyzers/WTG.Analyzers.csproj

Visual studio ignores `.editorconfig` when editing the project file via 'Solution Explorer', but not when editing as an xml file. This change sets the settings for project files to match what `Solution Explorer` uses anyway so that the saved content doesn't keep jumping back and forth.

Avoid fights with visual studio.

---

WTG.Analyzers.Utils.Test/ExpressionSyntaxFactoryTest.cs
WTG.Analyzers.Utils/ExpressionRemover.cs
WTG.Analyzers.Utils/ExpressionSyntaxFactory.cs
WTG.Analyzers/Analyzers/BooleanComparison/BooleanComparisonCodeFixProvider.cs

There are a number of places where the code fixes need to invert a boolean expression, currently we do this by simply applying the `!` operator.
This change considers the expression to be inverted so that, for example:
* `a != null` -> `a == null`
* `!string.IsNullOrEmpty(a)` -> `string.IsNullOrEmpty(a)`
* `a >= 0` -> `a < 0`

Improved bool inversion.

---

README.md

AppVeyor links in README.md should reference the latest build _on master_ rather than latest build overall.

README.md AppVeyor links to master branch.

---

WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/Generic/Diagnostics.xml
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/Generic/Source.cs
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/NestedMethods/Diagnostics.xml
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/NestedMethods/Result.cs
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/NestedMethods/Source.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsHelper.cs

* Local methods, anonymous methods and lambda expressions should be treated as 'private'.
* The exception extracted from `Requires<>` should be simplified (though, it's not moving between contexts so the benefit here is marginal at best).

Code contracts revised

---

WTG.Analyzers.Test/TestData/AsyncAnalyzer/AnonymousMethod/Diagnostics.xml
WTG.Analyzers.Test/TestData/AsyncAnalyzer/AnonymousMethod/Result.cs
WTG.Analyzers.Test/TestData/AsyncAnalyzer/AnonymousMethod/Source.cs
WTG.Analyzers.Test/TestData/AsyncAnalyzer/DirectMethod/Diagnostics.xml
WTG.Analyzers.Test/TestData/AsyncAnalyzer/DirectMethod/Result.cs
WTG.Analyzers.Test/TestData/AsyncAnalyzer/DirectMethod/Source.cs
WTG.Analyzers.Test/TestData/AsyncAnalyzer/Lambda/Diagnostics.xml
WTG.Analyzers.Test/TestData/AsyncAnalyzer/Lambda/Result.cs
WTG.Analyzers.Test/TestData/AsyncAnalyzer/Lambda/Source.cs
WTG.Analyzers.Test/TestData/AsyncAnalyzer/LocalMethod/Diagnostics.xml
WTG.Analyzers.Test/TestData/AsyncAnalyzer/LocalMethod/Result.cs
WTG.Analyzers.Test/TestData/AsyncAnalyzer/LocalMethod/Source.cs
WTG.Analyzers/Analyzers/Async/AsyncAnalyzer.cs

Fixes #51 
Passing a literal true into `ConfigureAwait` is now considered 'ok', all other values will continue to trip the WTG2001 warning when called from within an `async void` method.

Relax WTG2001 to allow literal true.

---

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers.Test/AnalyzerOnlyTest.cs
WTG.Analyzers.Test/TestData/ToStringAnalyzer/Enum/OldLanguageVersion/Diagnostics.xml
WTG.Analyzers.Test/TestData/ToStringAnalyzer/Enum/OldLanguageVersion/Source.cs
WTG.Analyzers.Test/TestData/VarAnalyzer/IgnoreStackallocSpan/Diagnostics.xml
WTG.Analyzers.Test/TestData/VarAnalyzer/IgnoreTargetTypedDefault/Diagnostics.xml
WTG.Analyzers.Test/TestData/VisibilityAnalyzer/DetectAndFix/Diagnostics.xml
WTG.Analyzers.Test/WTG.Analyzers.Test.csproj
WTG.Analyzers.TestFramework.Test/CodeFixerTest.cs
WTG.Analyzers.TestFramework/Helpers/CodeFixer.cs
WTG.Analyzers.TestFramework/Helpers/DiagnosticUtils.cs
WTG.Analyzers.TestFramework/Helpers/ModelUtils.cs
WTG.Analyzers.TestFramework/TestData/SampleDataSet.cs
WTG.Analyzers/Analyzers/ToString/ToStringAnalyzer.cs

Check the language version on the `SyntaxTree.Options` to see if `nameof` is even supported before suggesting we use it.

Nameof language version

---

WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/ForAll/Diagnostics.xml
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/ForAll/Result.cs
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/Requires/ForAll/Source.cs
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/SuppressMessage/Diagnostics.xml
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/SuppressMessage/Result.cs
WTG.Analyzers.Test/TestData/CodeContractsAnalyzer/SuppressMessage/Source.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsAnalyzer.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsCodeFixProvider.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsFixAllProvider.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsHelper.cs
WTG.Analyzers/Analyzers/CodeContracts/CodeContractsUsingSimplifier.cs

- Remove `SuppressMessage("Microsoft.Contracts", ...)`
- Remove preconditions that invoke `Contract.ForAll`
This synchronizes the rule with our dedicated internal tool. I've added equivalent unit tests to the internal tool's tests.
Resolves #77.

Remove additional Code Contracts bits and bobs

---

WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/ComplexConversion/Diagnostics.xml
WTG.Analyzers.Test/TestData/EmitAnalyzer/ComplexConversion/Result.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/ComplexConversion/Source.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/CorrectOverloads.Source.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/Fixable/Diagnostics.xml
WTG.Analyzers.Test/TestData/EmitAnalyzer/Fixable/Result.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/Fixable/Source.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/NonStandardFormat/Diagnostics.xml
WTG.Analyzers.Test/TestData/EmitAnalyzer/NonStandardFormat/Result.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/NonStandardFormat/Source.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/NotFixable/Diagnostics.xml
WTG.Analyzers.Test/TestData/EmitAnalyzer/NotFixable/Source.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/Uncast/Diagnostics.xml
WTG.Analyzers.Test/TestData/EmitAnalyzer/Uncast/Result.cs
WTG.Analyzers.Test/TestData/EmitAnalyzer/Uncast/Source.cs
WTG.Analyzers.Utils.Test/ExpressionSyntaxFactoryTest.cs
WTG.Analyzers.Utils/ExpressionSyntaxFactory.cs
WTG.Analyzers/Analyzers/Emit/EmitAnalyzer.cs
WTG.Analyzers/Analyzers/Emit/EmitCodeFixProvider.cs
WTG.Analyzers/Analyzers/Emit/EmitConversionVisitor.cs
WTG.Analyzers/Analyzers/Emit/EmitMatrix.cs
WTG.Analyzers/Analyzers/Emit/EmitMatrix.g.cs
WTG.Analyzers/Analyzers/Emit/EmitMatrix.tt
WTG.Analyzers/Analyzers/Emit/FieldAccessor.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml
WTG.Analyzers/WTG.Analyzers.csproj

Adds a rule to validate that the `ILGenerator.Emit` overload used is valid for specified `OpCode`. This is because the overload determines what bytes are emitted for the argument, but the opcode determines how those bytes will be interpreted ... and the emit method generally doesn't verify that they are the same.

Added Emit overload usage analyzer.

---

WTG.Analyzers.TestFramework.nuspec
WTG.Analyzers.Utils.nuspec

If I update NuGet.CommandLine or start using `dotnet pack`, then I start getting the [NU5128](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128) warning. This fixes the warning in preparation for whichever approach we eventually decide to take.
> WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location.
Also, since WTG.Analyzers.TestFramework is already building a netstandard2.0 version, I figured we might as well stick it in the nuget package too.

Fix NU5128 warning.

---

CommonAssemblyInfo.cs
Directory.Build.props

The CommonAssemblyInfo.cs file has long since been superseded by the build-time generated AssemblyInfo files. The only thing CommonAssemblyInfo.cs does now is disabling com visibility, but I don't think we need to care about that (We used to add it to satisfy legacy FxCop, but FxCopAnalyzers doesn't seem to care).

Removed CommonAssemblyInfo.cs

---

WTG.Analyzers.TestFramework/Helpers/CodeFixer.cs
WTG.Analyzers/Analyzers/Var/VarCodeFixProvider.cs

Currently `CodeFixer` asks the `CodeFixProvider` to fix all reported issues, including those not actually reported by the corresponding analyzer (which occasionally results in an invalid exception). This also means that our tests didn't notice when a `CodeFixProvider` failed to report all the issue ids that it can fix.

CodeFixer should only attempt to fix the fixable issues.

---

WTG.Analyzers.Test/TestData/RegexAnalyzer/InvokeNotOnIdentifier.Source.cs
WTG.Analyzers.TestFramework/Helpers/DiagnosticUtils.cs
WTG.Analyzers/Analyzers/Regex/RegexAnalyzer.cs

Fixes #110 
Also, the test framework was ignoring AD0001 diagnostics because they are warnings and not errors.

FIX NRE in RegexAnalyzer when invoking a return result.

---

WTG.Analyzers.Test/AnalyzerOnlyTest.cs
WTG.Analyzers.Test/TestData/HttpReasonPhraseAnalyzer/HttpResponseMessage/Diagnostics.xml
WTG.Analyzers.Test/TestData/HttpReasonPhraseAnalyzer/HttpResponseMessage/Source.cs
WTG.Analyzers.Test/TestData/HttpReasonPhraseAnalyzer/IHttpResponseFeature/Diagnostics.xml
WTG.Analyzers.Test/TestData/HttpReasonPhraseAnalyzer/IHttpResponseFeature/Source.cs
WTG.Analyzers.Test/TestData/HttpReasonPhraseAnalyzer/NotWellKnownClass/Source.cs
WTG.Analyzers/Analyzers/HttpReasonPhrase/HttpReasonPhraseAnalyzer.cs
WTG.Analyzers/Rules/Rules.g.cs
WTG.Analyzers/Rules/Rules.xml

The HTTP ReasonPhrase value is a standard human-readable field that accompanies the status code with a reason for it, e.g. 
```plain
HTTP/1.1 200 OK
```
or
```plain
HTTP/1.1 405 Method Not Allowed
```
This can be customised by the server, e.g.:
```plain
HTTP/1.1 200 I'm A Little Teapot Short And Stout
```
Unfortunately there is no guarantee in HTTP/1.0 and HTTP/1.1 that intermediate proxy server will preserve these customised values all the way between the server and client.
Furthermore, in HTTP/2, the ReasonPhrase field has been dropped entirely, leaving only the status code: https://github.com/http2/http2-spec/issues/202
As a part of WI00294611, this PR adds a new analyzer to detect when people set a custom value on [`HttpResponseMessage`](https://docs.microsoft.com/en-us/dotnet/api/syst …

Add analyzer to forbid setting custom HTTP ReasonPhrase values

---

WTG.Analyzers.Test/TestData/BooleanLiteralAnalyzer/UnnamedMethodArgumentInAnExpressionTree/Source.cs
WTG.Analyzers/Analyzers/BooleanLiteral/BooleanLiteralAnalyzer.cs

> CS0853: An expression tree may not contain a named argument specification.
Whoopsie!

WTG2007 should not trigger in an expression as it will cause CS0853

---

WTG.Analyzers.Test/TestData/BooleanLiteralAnalyzer/UnnamedMethodArgumentPriorToCSharp4/Diagnostics.xml
WTG.Analyzers.Test/TestData/BooleanLiteralAnalyzer/UnnamedMethodArgumentPriorToCSharp4/Source.cs
WTG.Analyzers/Analyzers/BooleanLiteral/BooleanLiteralAnalyzer.cs

Named arguments were only introduced in C# 4.0.
Fixes #131.

Suppress BooleanLiteralAnalyzer on C# versions prior to 4.0

---

WTG.Analyzers.Test/WTG.Analyzers.Test.csproj
WTG.Analyzers.TestFramework.Test/WTG.Analyzers.TestFramework.Test.csproj
WTG.Analyzers.Utils.Test/WTG.Analyzers.Utils.Test.csproj

We don't need it now that we use github workflows rather than AppVeyor, and it causes issues with package management.

Removed the 'embed target framework in assembly name' hack.

---

WTG.Analyzers.Test/TestData/PointlessOverrideAnalyzer/Attributes/Source.cs
WTG.Analyzers/Analyzers/PointlessOverride/PointlessOverrideAnalyzer.cs

This is something I came across while reading through the API proposal for the new Secret<T> type and the recent [API review notes](https://github.com/dotnet/designs/pull/147#issuecomment-844392771).

Overrides with additional attributes aren't entirely pointless.

---

src/WTG.Analyzers.Test/TestData/StringBuilderAppendAnalyzer/StringConstructor/CharBuffer/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/StringBuilderAppendAnalyzer/StringConstructor/CharBuffer/Result.cs
src/WTG.Analyzers.Test/TestData/StringBuilderAppendAnalyzer/StringConstructor/CharBuffer/Source.cs
src/WTG.Analyzers.Test/TestData/StringBuilderAppendAnalyzer/StringConstructor/RepeatedChar/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/StringBuilderAppendAnalyzer/StringConstructor/RepeatedChar/Result.cs
src/WTG.Analyzers.Test/TestData/StringBuilderAppendAnalyzer/StringConstructor/RepeatedChar/Source.cs
src/WTG.Analyzers/Analyzers/StringBuilderAppend/StringBuilderAppendAnalyzer.cs
src/WTG.Analyzers/Analyzers/StringBuilderAppend/StringBuilderAppendCodeFixProvider.cs

Extend WTG3011 to cover the following cases:
```csharp
builder.Append(new string(c, repeat)); // string(char, int)
builder.Append(new string(buffer)); // string(char[])
builder.Append(new string(buffer, start, length)); // string(char[], int, int)
```
The code fixes should rewrite them to:
```csharp
builder.Append(c, repeat); // string(char, int)
builder.Append(buffer); // string(char[])
builder.Append(buffer, start, length); // string(char[], int, int)
```

Extend WTG3011 to cover some string constructors.

---

src/WTG.Analyzers.Test/AnalyzerAndCodeFixTest.cs
src/WTG.Analyzers.Test/TestData/BooleanLiteralCombiningAnalyzer/NoAutoFix/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/BooleanLiteralCombiningAnalyzer/NoAutoFix/Source.cs
src/WTG.Analyzers.TestFramework/Helpers/CodeFixUtils.cs
src/WTG.Analyzers.TestFramework/Helpers/CodeFixer.cs
src/WTG.Analyzers.TestFramework/Helpers/ModelUtils.cs
src/WTG.Analyzers.TestFramework/TestData/SampleDataSet.cs
src/WTG.Analyzers.TestFramework/TestData/SampleDataSetOptions.cs
src/WTG.Analyzers/Analyzers/BooleanLiteralCombining/BooleanLiteralCombiningAnalyzer.cs
src/WTG.Analyzers/Analyzers/BooleanLiteralCombining/BooleanLiteralCombiningCodeFixProvider.cs

Fixes #168 
Don't offer to fix value coercion expressions, eg.
```csharp
x || true
x && false
```

Don't offer to fix value coercion expressions.

---

Directory.Build.props

This isn't strictly necessary but it does keep it consistent.

Bump version number for 3.7.1 release

---

src/WTG.Analyzers.Test/TestData/BooleanLiteralCombiningAnalyzer/AndOrAssignment/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/BooleanLiteralCombiningAnalyzer/AndOrAssignment/Result.cs
src/WTG.Analyzers.Utils.Test/ExpressionRemoverTest.cs
src/WTG.Analyzers.Utils/ExpressionRemover.cs

fixes #191
When collapsing an and/or assignment to just the LHS, we mark it as "weak". When visiting an ExpressionStatement, we can detect the weak expression and return the "discardable" empty statement. There is already logic to dissolve the discardable empty statement if it happens to land in a BlockStatement.

Try to avoid CS0201 when collapsing away and/or assignments.

---

src/WTG.Analyzers.Test/TestData/VarAnalyzer/Foreach/Result.cs
src/WTG.Analyzers.Test/TestData/VarAnalyzer/Foreach/Source.cs
src/WTG.Analyzers.Utils.Test/EnumerableTypeUtilsTest.cs
src/WTG.Analyzers.Utils/EnumerableTypeUtils.cs

This comes from the case discussed in Teams.
When a foreach-able object is invoked via a subclass, we don't necessarily locate the correct `GetEnumerator` method. This PR fixes `EnumerableTypeUtils.GetElementType` to check the base classes as well.
Tracked by WI00633703.

Fix WTG1002 false-positive in enumerable subclasses

---

Directory.Build.props

This isn't strictly necessary but it does keep it consistent.

Bump version number for 3.7.2 release

---

.github/workflows/build.yaml
.github/workflows/release.yaml

We shouldn't need this anymore - it was fixed by https://github.com/actions/runner-images/pull/3144 three years ago.

Remove old CI workaround

---

src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/Partial/Diagnostics.xml
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/Partial/Result.cs
src/WTG.Analyzers.Test/TestData/VisibilityAnalyzer/Partial/Source.cs
src/WTG.Analyzers/Analyzers/Visibility/VisibilityAnalyzer.cs

Fix #224 
Tracked by [WI00764889](https://svc-ediprod.wtg.zone/Services/link/ShowEditForm/WorkItem/75870954-7a36-4dc4-9e37-806a85aa3bb2?lang=en-gb)
- A method with default access modifier, partial, return value
e.g. private partial int Bar(); // no error as it returns value
- A partial method with non-default access modifier, void
e.g. public partial void Bar(); // no error as it returns value
- A partial method with default access modifier, void
e.g. private partial void Bar(); // trigger WTG1001 and remove 'private' when code-fix run
- A partial method with default access modifier, void, out value
e.g. private partial void Bar(out int value); // no error as it 'out' a value
- A partial method with default access modifier, return value, out value
e.g. private partial int Bar(out int …

Cover WTG1001 on edge cases
